//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Source.rc
//
#define ID_DELETEEVENT                  3
#define IDC_ENTER_CODE                  3
#define IDHIDE                          3
#define ID_SPEECH_PROPERTIES            3
#define ID_EDIT_SMTP                    3
#define ID_EDITEVENT                    4
#define IDC_PURCHASE                    4
#define ID_ADDEVENT                     5
#define ID_RUN_NOW                      6
#define ID_ENABLE                       7
#define ID_ADD_FOLDER                   8
#define IDD_ABOUT                       100
#define IDD_SOURCE_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_EVENTS                      129
#define IDD_EVENT                       130
#define IDB_LOGO                        130
#define IDD_MUTE                        131
#define IDD_TRIGGER                     132
#define IDD_TRIGGER_TIME                133
#define IDD_ACTION_MESSAGE              134
#define IDD_TOKENS                      134
#define IDD_ACTION                      135
#define IDD_ACTION_SOUND                136
#define IDD_KEY_LOG                     138
#define IDD_TRIGGER_HOTKEY              139
#define IDD_ACTION_WEBSITE              140
#define IDD_OPTIONS                     145
#define IDR_TRAY_MENU                   148
#define IDD_ACTION_COMPARE              149
#define IDR_COPY_MENU                   149
#define IDR_MENU_WIZARD                 150
#define IDD_WIZARD                      152
#define IDD_OKCANCEL                    153
#define IDD_THREADS                     154
#define IDD_NAG                         155
#define IDD_UNLOCK                      156
#define IDD_RENAME                      157
#define IDD_WELCOME                     158
#define IDD_VOICE                       161
#define IDD_TEST                        162
#define IDD_TIME_RANGE                  163
#define IDD_TRIGGER_INACTIVITY          164
#define IDD_ACTION_RUN                  165
#define IDD_QUIT                        166
#define IDD_ACTION_STEALTH              167
#define IDD_ACTION_EMAIL                168
#define IDD_EMAIL_SETTINGS              169
#define IDD_SMTP_SETUP                  170
#define IDD_ACTION_TOGGLE               171
#define IDD_INTRO                       172
#define IDD_WIZARD_ONE_TIME_REMINDER    173
#define IDR_FISH_DISABLED               174
#define IDD_ACTION_ATOMIC               176
#define IDD_WIZARD_RECURRENT_REMINDER   177
#define IDD_TRIGGER_DAY_FILTER          178
#define IDD_WIZARD_ATOMIC               179
#define IDD_ALERT                       180
#define IDD_ACTION_TTS                  181
#define IDD_ACTION_SMARTMUTE            182
#define IDD_ACTION_VOLUME               183
#define IDD_WIZARD_EMAIL                184
#define IDD_MAIL_VIEW                   186
#define IDD_ACTION_MONITOR              187
#define IDD_WIZARD_MONITOR              188
#define IDD_FUN                         190
#define IDD_STATISTICS                  191
#define IDD_TRIGGER_PROCESS             192
#define IDD_ACTION_SEND                 194
#define IDD_ACTION_DELAY                196
#define IDD_ACTION_REBOOT               197
#define IDD_ACTION_LEET                 198
#define IDD_WIZARD_ONE_TIME_REMINDER_X  199
#define IDD_DIALOG1                     200
#define IDD_ACTION_MIC_VOLUME           201
#define IDD_DIALOG2                     202
#define IDD_ACTION_REZ                  202
#define IDR_FOLDER                      203
#define IDR_FOLDER_OPEN                 204
#define IDR_FISH_ALARM                  205
#define IDR_FISH_ONETIME                206
#define IDC_ABOUT                       1000
#define IDC_EVENTS                      1001
#define IDC_KEY_LOG                     1002
#define IDC_SLIDER                      1002
#define IDC_OPTIONS                     1003
#define IDC_LOG                         1004
#define IDC_MUTE                        1005
#define IDC_SAY_IT                      1005
#define IDC_OK                          1006
#define IDC_PLAY_SOUND                  1006
#define IDC_TRIGGER_ADD                 1007
#define IDC_CANCEL                      1007
#define IDC_SUGGEST                     1007
#define IDC_POP_UP                      1007
#define IDC_ACTION_ADD                  1008
#define IDC_WIZARD                      1008
#define IDC_BROWSER                     1008
#define IDC_RADIO_SECONDS               1009
#define IDC_TRIGGER_DELETE              1009
#define IDC_WEBSITE                     1009
#define IDC_CLEAR                       1009
#define IDC_RADIO_MINUTES               1010
#define IDC_TRIGGER_EDIT                1010
#define IDC_BUT_HELP                    1010
#define IDC_MUTE_ENABLED                1011
#define IDC_ACTION_DELETE               1011
#define IDC_UPGRADE                     1011
#define IDC_EMAILVIEW                   1011
#define IDC_TRIGGER_LIST                1012
#define IDC_ABOUT_STATIC                1012
#define IDC_FUN                         1012
#define IDC_ACTION_LIST                 1013
#define IDC_MHELP                       1013
#define IDC_ACTION_EDIT                 1014
#define IDC_ENABLED                     1015
#define IDC_BOOT_LOAD                   1015
#define IDC_NAME                        1016
#define IDC_BOOT_STEALTH                1016
#define IDC_PASSWORD                    1017
#define IDC_BLINK_WEBPAGE               1017
#define IDC_LIST                        1018
#define IDC_FILTER_TEXT                 1018
#define IDC_BLINK_EMAIL                 1018
#define IDC_TIME                        1021
#define IDC_RESCHEDULE_ACTIVE           1022
#define IDC_MONTHCALENDAR1              1023
#define IDC_RESCHEDULE_TIME             1024
#define IDC_RADIO_HOURS                 1025
#define IDC_B_LOG                       1025
#define IDC_B_KEY_LOG_ACTIVE            1025
#define IDC_RADIO_DAYS                  1026
#define IDC_B_POPUP                     1026
#define IDC_LOG_BROWSE                  1026
#define IDC_B_SAY                       1027
#define IDC_KEY_LOG_FILE                1027
#define IDC_B_MACRO                     1028
#define IDC_B_PROG_LOG                  1028
#define IDC_B_EMAIL                     1029
#define IDC_FONT                        1031
#define IDC_VIEW_LOG                    1033
#define IDC_RICHEDIT                    1034
#define IDC_DELETE_LOG                  1034
#define IDC_FILENAME                    1035
#define IDC_BROWSE                      1036
#define IDC_PORT                        1036
#define IDC_SIZE_BYTES                  1037
#define IDC_COMBO                       1038
#define IDC_ST_WORDS_FOUND              1038
#define IDC_B_ALT                       1039
#define IDC_ST_WORDS_NOT_FOUND          1039
#define IDC_B_CTRL                      1040
#define IDC_TEST                        1040
#define IDC_B_SHIFT                     1041
#define IDC_ST_AUTH_LOGON               1041
#define IDC_ST_AUTH_PASSWORD            1043
#define IDC_EVENT_NAME                  1046
#define IDC_EDIT_CONTEST_PERCENT        1048
#define IDC_EDIT_CHECK_TIME             1049
#define IDC_CHECK_CONTENT               1052
#define IDC_CHECK_DATE                  1053
#define IDC_CHECK_WORDS_FOUND           1054
#define IDC_CHECK_WORDS_NOT_FOUND       1055
#define IDC_GROUPBOX                    1060
#define IDC_GROUPBOX1                   1061
#define IDC_GROUPBOX2                   1062
#define IDC_TRIGGER_DOWN                1063
#define IDC_TRIGGER_UP                  1064
#define IDC_ACTION_DOWN                 1065
#define IDC_ACTION_UP                   1066
#define IDC_EDIT1                       1066
#define IDC_LOG_LINES                   1066
#define IDC_KEY                         1066
#define IDC_SAY                         1066
#define IDC_EDIT                        1066
#define IDC_SERVER                      1066
#define IDC_MAIL_TO                     1066
#define IDC_SEARCH                      1066
#define IDC_MS                          1066
#define IDC_BUT_PIC                     1067
#define IDC_MAIL_FROM                   1067
#define IDC_MSG                         1067
#define IDC_PIC                         1068
#define IDC_MAIL_SUBJECT                1068
#define IDC_LPARAM                      1068
#define IDC_MAIL_FILE                   1069
#define IDC_WPARAM                      1069
#define IDC_LOG_IT                      1071
#define IDC_EDIT_CONTENT_PERCENT        1072
#define IDC_RICHEDIT1                   1073
#define IDC_TRIM_LOG                    1074
#define IDC_TEXT                        1076
#define IDC_LOGO                        1077
#define IDC_STATUS                      1080
#define IDC_NAG_TEXT                    1081
#define IDC_BUT_RTSOFT                  1082
#define IDC_TOOLFISH_HELP               1083
#define IDC_LAST_RUN                    1084
#define IDC_NEXT_RUN                    1085
#define IDC_RENAME                      1086
#define IDC_BUT_TIP1                    1088
#define IDC_BUT_TIP2                    1089
#define IDC_BUT_TIP3                    1090
#define IDC_RTSOF                       1091
#define IDC_BUT_TIP4                    1091
#define IDC_HEAR                        1093
#define IDC_PITCH_SLIDER                1094
#define IDC_PITCH_SPEED                 1095
#define IDC_VOICE_CONFIGURE             1095
#define IDC_HTML                        1096
#define IDC_SMTP_CONFIGURE              1096
#define IDC_TIME_START                  1097
#define IDC_TIME_END                    1098
#define IDC_RADIO_HAS                   1098
#define IDC_RADIO_HAS_NOT               1099
#define IDC_EDIT_PARMS                  1102
#define IDC_CHECK_WAIT                  1103
#define IDC_B_DISABLE_TTS               1105
#define IDC_B_DETECT_IP_SERVER_SIDE     1106
#define IDC_PASS_THROUGH                1107
#define IDC_B_MINIMIZE_ON_CLOSE         1107
#define IDC_SAY_COUNT                   1110
#define IDC_SAY_FROM                    1111
#define IDC_EMAIL                       1111
#define IDC_SAY_SUBJECT                 1112
#define IDC_DEFAULT_EMAIL               1112
#define IDC_USERNAME                    1113
#define IDC_QUIET                       1114
#define IDC_AUTO_DELETE_AFTER_RUNNING   1115
#define IDC_BUTTON2                     1116
#define IDC_TOKEN                       1118
#define IDC_TREE                        1121
#define IDC_FILTER_ACTIVE               1122
#define IDC_FILTER_HAVE                 1123
#define IDC_FILTER_FIELD                1126
#define IDC_MONTHCALENDAR               1126
#define IDC_DAY1                        1134
#define IDC_DAY2                        1135
#define IDC_DAY0                        1136
#define IDC_DAY3                        1137
#define IDC_DAY4                        1138
#define IDC_DAY5                        1139
#define IDC_DAY6                        1140
#define IDC_GROUPBOX3                   1142
#define IDC_COMBO_TIME                  1144
#define IDC_B_ENABLE_TRAY               1146
#define IDC_DISABLE                     1149
#define IDC_UNMUTE                      1151
#define IDC_FADE                        1152
#define IDC_IGNORE_LATE                 1152
#define IDC_TIMEOUT                     1154
#define IDC_RESET                       1155
#define IDC_ERROR                       1157
#define IDC_SIZE_CONTENT                1158
#define IDC_WEBPAGE                     1159
#define IDC_TEXT1                       1160
#define IDC_TEXT2                       1161
#define IDC_REVERSE                     1162
#define IDC_POPUP                       1163
#define IDC_EMAIL_TO                    1164
#define IDC_SMTP                        1165
#define IDC_EMAIL_FROM                  1168
#define IDC_LOGON                       1169
#define IDC_MIME                        1171
#define IDC_FIND_FILE                   1173
#define IDC_STATISTICS                  1174
#define IDC_OVERLAY                     1175
#define IDC_TODAY_KEY                   1177
#define IDC_TODAY_MOUSE                 1178
#define IDC_TOTAL_KEY                   1179
#define IDC_TOTAL_MOUSE                 1180
#define IDC_TODAY_BUTTONS               1181
#define IDC_TOTAL_BUTTONS               1182
#define IDC_FOUND                       1183
#define IDC_FOCUS                       1185
#define IDC_RADIO1                      1187
#define IDC_RADIO2                      1188
#define IDC_COMBO_MESSAGE               1190
#define IDC_RADIO3                      1191
#define IDC_COMBO_KEY                   1193
#define IDC_VIEW                        1194
#define IDC_NEW                         1197
#define IDC_AUTHENTICATION              1199
#define IDC_DESCRIPTION                 1201
#define IDC_PARTIAL_NAME                1202
#define IDC_VOLUME_KNOB_ENABLED         1203
#define IDC_VOLUME_KNOB_MULTIPLIER      1204
#define IDC_VOLUME_KNOB_SHIFT_ONLY      1205
#define IDC_VOLUME_KNOB_GROUP           1206
#define ID_MENU_EXIT                    32772
#define ID_MENU_OPTIONS                 32773
#define ID_MENU_COPY                    32774
#define ID_MENU_WIZARD_WEB              32775
#define ID_MENU_WIZARD_REMINDER         32776
#define ID_MENU_WIZARD_ONE_TIME_REMINDER 32777
#define ID_MENU_VOICE_MUTE              32778
#define ID_ABOUT_TOOLFISH               32779
#define ID_DISABLE_SMARTMUTE            32780
#define ID_MENU_WIZARD_ATOMIC           32781
#define ID_MENU_READ_CLIPBOARD          32782
#define ID_MENU_WIZARD_EMAIL            32783
#define ID_MENU_WIZARD_MONITOR          32784
#define ID_MENU_WIZARD_REMINDER_5       32786
#define ID_MENU_WIZARD_REMINDER_10      32788
#define ID_MENU_WIZARD_REMINDER_15      32789
#define ID_MENU_WIZARD_REMINDER_30      32790
#define ID_MENU_WIZARD_REMINDER_1_HOUR  32791
#define ID_MENU_WIZARD_REMINDER_2_HOUR  32792
#define ID_MENU_WIZARD_REMINDER_4_HOURS 32793
#define ID_MENU_WIZARD_REMINDER_8_HOURS 32794
#define ID_MENU_WIZARD_REMINDER_1_DAY   32795
#define ID_MENU_WIZARD_REMINDER_1_WEEK  32796
#define ID_MENU_WIZARD_REMINDER_1_MONTH 32797
#define ID_MENU_WIZARD_REMINDER_20      32798
#define ID_MENU_WIZARD_REMINDER_45      32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1207
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
